### ISSUE TITLE
there is no template with dashboard, but it is in the screenshots

### ISSUE THREAD

**Issue by artempogor** [Miaababikir/Laravel-Tailwind-CSS-Dashboard-Preset#10]
there is no template with dashboard, but it is in the screenshots

**Comment by Miaababikir** [comment]
@artempogor It is on `/ui` route, try it let me know

**Comment by artempogor** [comment]
![image](https://user-images.githubusercontent.com/24799458/128984068-162b97a8-a015-4b11-8dd1-83ea10b9ce37.png)

**Comment by artempogor** [comment]
Moreover, after running php artisan ui tailwind-dashboard --option = vue.sidebar command and npm install && npm run dev gives errors
![image](https://user-images.githubusercontent.com/24799458/129043051-506cf76f-4222-4070-b289-6979aa243e01.png)

**Comment by Miaababikir** [comment]
@artempogor I just fixed the issues, you can try upgrading the package and it will work
