### ISSUE TITLE
Dynamic sidebar

### ISSUE THREAD

**Issue by viniciushsantana** [Miaababikir/Laravel-Tailwind-CSS-Dashboard-Preset#2]
Hi there,

I've started using this preset and I'm wondering what are the best practices around the sidebar component.

Is there any links on how I should update the sidebar entries and of course, the change selected entry based on the current page?

Thanks!

**Comment by Miaababikir** [comment]
Hi,

If I understand you correctly, most of the time I am just adding the links manually, but in some projects, I end up creating an array of all the links that I want to add to the sidebar or the navbar

I end up with something like this on the sidebar component and I loop through it or maybe you can pass it down as a props to the component.
``` js
links: [
    { name: 'Home', url: '/home', icon: 'icon svg' },
    { name: 'Users', url: '/users', icon: 'icon svg' },
]
```

Another way you can create a model or configuration file on the backend for all your links and pass it down to the component.

I really don't know if these are best practices or not, I will search more about this topic and I will let you know if I found anything helpful, also if you found anything helpful let me know.

And also for the selected entry on the vue side, I always use [Ziggy](https://github.com/tightenco/ziggy), With it you can use your laravel named routes on vue, and also you can use most of the helper method that comes with laravel route like `current` or `is` and more.

Here is an example for checking the current url
``` js
route().current('events.index');
// returns true

route().current('events.*');
// returns true
```

Also if you are using just blade for the sidebar you can check this [article](https://quickadminpanel.com/blog/laravel-how-to-make-menu-item-active-by-urlroute/)
