### ISSUE TITLE
Component Request

### ISSUE THREAD

**Issue by FoksVHox** [Miaababikir/Laravel-Tailwind-CSS-Dashboard-Preset#5]
Hi!

I'd like to request a few advanced components for this repo.

List of components

- Searchable select
  - Ability to search through the select
- Modals

**Comment by Miaababikir** [comment]
@FoksVHox  Hey! 👋 

Did you try using [Vue Modal](https://github.com/euvl/vue-js-modal) and [Vue select](https://github.com/sagalbot/vue-select) they did a great work implementing these components.

Also to verify that I understand you will, do you mean you want the components with it functionality or just the design? or you need some wrapper components for these libraries using tailwind

**Comment by FoksVHox** [comment]
> Did you try using Vue Modal and Vue select they did a great work implementing these components.

I'm not using Vue, so it wouldn't make sense to have random vue components in my app imo.

> Also to verify that I understand you will, do you mean you want the components with it functionality or just the design? or you need some wrapper components for these libraries using tailwind'

I would prefer a functional component that works

**Comment by Miaababikir** [comment]
Sorry Buddy I am not planning to implement it right now, But I will think about it.
